### ISSUE TITLE
Feature request; polygon extent

### ISSUE THREAD

**Issue by yurukov** [d3/d3-voronoi#25]
I have a viz I want to make where I have a map segmented along district lines. I have points in each district and want to do a voronoi segmentation of that district along certain points. I would like to use the district polygon outline as extent, instead of a triangle.

**Comment by mbostock** [comment]
I think it’s unlikely that we’re going to implement arbitrary clipping of 2D polygons, but if we do, it would be in the d3-polygon repo rather than here; see d3/d3-polygon#4. See also this [JavaScript implementation of Greiner–Hormann](https://github.com/w8r/GreinerHormann).

Alternatively, you can use SVG or Canvas clipping to clip the Voronoi diagram rather than doing it in JavaScript.

**Comment by yurukov** [comment]
I agree, that's what I ended up doing - clipping the paths with the region path.
